(CustomerShared)..>(Customer)
(HandlingEvent)..>(CarrierMovement)
(HandlingEvent)..>(Cargo)
(DeliverySpecification)..>(LocationShared)
(CarrierMovement)..>(LocationShared)
(CarrierMovement)..>(Location)
(Cargo)..>(Customer)
(Cargo)..>(DeliveryHistory)
(Cargo)..>(CustomerShared)
(Cargo)..>(DeliverySpecification)
(LocationShared)..>(Location)
(DeliveryHistory)..>(HandlingEvent)
